title: DavM25
description: 
author: DavM25
avatar: /logo.png
email: 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: G-6724CKY8CJ

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus: 

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: DavM25
  card: summary
logo: logo.png
social:
  name: DavM25
  links:
    - https://twitter.com/dav_m25
    - https://github.com/davm25
    - https://app.hackthebox.com/users/418825
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es

location: Barcelona, Espa√±a
skin: midnight

subscribe: false
